version: "3.8"
services:
  spire-server:
    image: ghcr.io/spiffe/spire-server:1.6.5
    container_name: spire-server
    volumes:
      - ./spire-config:/spire-config
    command: ["-config", "/spire-config/server.conf"]
    networks:
      - spiffe-net

  spire-agent:
    image: ghcr.io/spiffe/spire-agent:1.6.5
    container_name: spire-agent
    depends_on: [spire-server]
    volumes:
      - ./spire-config:/spire-config
      - /run/spire:/run/spire
    command: ["-config", "/spire-config/agent.conf"]
    networks:
      - spiffe-net

networks:
  spiffe-net:
